### PR TITLE
small edits to verbatastic

### PR DESCRIPTION
**Pull request by evexwening**
made it load slightly faster / display 'x and y' if only two usernames

### CODE REVIEW

**Review by Rydak87 — CHANGES_REQUESTED** [review]
Screenshot 2023-11-10 at 10 52 00 AM


getting weird things with the global challenge stats. I have two users who have answered "Bamboo" and "baritone" to the second question but under friend's answers it says "bambi" which was Johndoe's response to the first question. "bambi" also shows up on the third question as well.

**Comment by Rydak87** [comment]
Same when I add a third user's response: Q1 response shows up for Q2 and Q3
Screenshot 2023-11-10 at 10 54 33 AM

**Comment by evexwening** [comment]
> Same when I add a third user's response: Q1 response shows up for Q2 and Q3 Screenshot 2023-11-10 at 10 54 33 AM

thank you i never wld have found this because i always submit a keyboard smash. shld be fixed now plus i tried to make verbatim work for mobile but since i cant check it on a mobile i actually have no idea!

**Comment by Rydak87** [comment]
Looks better! Small thing but I got an overflow error on the stats page with a longish answer:
Screenshot 2023-11-10 at 11 08 30 AM

**Review by DahliaTheCoder — APPROVED** [review]

**Review by Rydak87 — APPROVED** [review]
lgtm!

**Pull request merged**
